insert into category(category_id, category_name) values ('1', 'Electronics');
insert into category(category_id, category_name) values ('2', 'Clothing');
insert into category(category_id, category_name) values ('3', 'Toys');

insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('1', '1', 'MacOS Screen', '20', '100', 'https://images.idgesg.net/images/article/2017/06/macos-sierra-homescreen-100724980-large.jpg');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('2', '1', 'Macbook Pro', '20', '200', 'https://www.igrossisti.eu/wp-content/uploads/2019/01/MACBOOK-PRO-15-TOUCHBAR-GREY.jpg');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('3', '1', 'Amazon Fire Stick', '20', '10', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5477/5477500_sd.jpg');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('4', '2', 'Running Shoes For Men', '20', '590', 'https://rukminim1.flixcart.com/image/880/1056/jynat8w0/shoe/w/k/2/m7-2-3-5-9-m7-by-metronaut-grey-black-original-imafgu8yrsvxsghx.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('5', '2', 'Printed Men Hooded Neck White T-Shirt', '20', '359', 'https://rukminim1.flixcart.com/image/880/1056/k01b8280/t-shirt/5/t/5/4xl-twthdful-just-tripr-original-imafjxcbxuenppat.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('6', '2', 'Slim Men Dark Blue Jeans', '20', '1199', 'https://rukminim1.flixcart.com/image/880/1056/k2arbm80/jean/x/z/b/32-xcya00317-b6-parx-original-imafhh57ucwx5pep.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('7', '2', 'Solid Men Grey Track Pants', '20', '649', 'https://rukminim1.flixcart.com/image/880/1056/jfea93k0/track-pant/h/w/8/l-jog18-d95-mil-alan-jones-original-imaf3va53zz9ggpj.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('8', '2', 'Camouflage Men Multicolor Track Pants', '20', '799', 'https://rukminim1.flixcart.com/image/880/1056/k0igia80/track-pant/b/a/v/36-camo-jogger-grey-36-zacharias-original-imafk9vbrsqgzspp.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('9', '2', 'Men Checkered Casual Spread Shirt', '20', '449', 'https://rukminim1.flixcart.com/image/880/1056/jvy4vbk0/shirt/b/v/x/m-hlsh009384-highlander-original-imafgqhfu3hprhmn.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('10', '2', 'Color Block Men Round Neck Dark Blue, Orange T-Shirt', '20', '399', 'https://rukminim1.flixcart.com/image/880/1056/k0sgl8w0/t-shirt/y/d/a/m-tnvorrnful-r5-tripr-original-imafkggneagxt843.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('11', '2', 'Solid Men Polo Neck Black, White T-Shirt', '20', '499', 'https://rukminim1.flixcart.com/image/880/1056/jm3ro280/t-shirt/9/h/f/m-style-tshirt-try-this-original-imaf8zxukgz3cjhq.jpeg?q=50');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('12', '3', 'Pikachu Model', '20', '100', 'https://www.toyworld.com.au/media/catalog/product/cache/3/small_image/360x/9df78eab33525d08d6e5fb8d27136e95/8/8/889933963831.jpg');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('13', '3', 'Avengers Ultron', '20', '100', 'https://cdn11.bigcommerce.com/s-0kvv9/images/stencil/1280x1280/products/281980/395677/apitymrvz__10747.1545411570.jpg?c=2&imbypass=on');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('14', '3', 'Bumblebee Action Figure', '20', '100', 'https://n3.sdlcdn.com/imgs/h/s/t/Darling-Toys-2-in-1-SDL547002629-1-4290f.jpeg');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('15', '3', 'Rubiks Cube', '20', '100', 'https://rukminim1.flixcart.com/image/612/612/jmi22kw0/puzzle/d/h/f/1-high-speed-stickerless-3x3-magic-rubik-cube-puzzle-game-toy-original-imaf8g4zyghejjkc.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('16', '1', 'IFB 6 kg 2D Wash Fully Automatic Front Load', '20', '20990', 'https://rukminim1.flixcart.com/image/832/832/k0r15e80/washing-machine-new/p/r/t/diva-aqua-vx-ifb-original-imafkh4jrftndzzj.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('17', '1', 'Carrier 1.5 Ton 3 Star Window AC - White', '20', '26999', 'https://rukminim1.flixcart.com/image/832/832/jtrjngw0/air-conditioner-new/p/f/3/18k-estra-neo-3-star-wrac-ac-r32-1-5-window-carrier-fixed-speed-original-imafesjfzh46pwsf.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('18', '1', 'Samsung 192 L Direct Cool Single Door 2 Star Refrigerator', '20', '12958', 'https://rukminim1.flixcart.com/image/832/832/jdlzfrk0/refrigerator-new/4/c/r/rr19n1112rz-hl-rr19n2112rz-nl-2-samsung-original-imaf2hd7tszkcfhb.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('19', '1', 'Onida 23 L Convection Microwave Oven', '20', '8350', 'https://rukminim1.flixcart.com/image/832/832/microwave-new/e/n/g/onida-mo23cjs11b-original-imae7tatptyyrzyf.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('20', '1', 'Sharp 101cm (40 inch) Full HD LED TV', '20', '19290', 'https://rukminim1.flixcart.com/image/832/832/jnyxd3k0/television/c/f/p/sharp-lc-40le185m-original-imafajgvyrbjqsjm.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('21', '1', 'Philips 98cm (39 inch) HD Ready LED TV', '20', '16990', 'https://rukminim1.flixcart.com/image/832/832/television/x/9/c/philips-39pfl3931-original-imaephzsdmuuhkes.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('22', '3', 'CRAWLING DOUBLE SIDE STUNT CAR', '20', '729', 'https://rukminim1.flixcart.com/image/832/832/k34rki80/remote-control-toy/e/g/h/2-4g-rc-crawling-double-side-stunt-car-with-light-miss-chief-original-imafmbgup2hxrch9.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('23', '3', 'AR Enterprises 37 Key Piano Keyboard Toy', '20', '599', 'https://rukminim1.flixcart.com/image/832/832/jdvziq80/musical-toy/v/z/u/37-key-piano-keyboard-toy-with-dc-power-option-mic-and-recording-original-imaf2pbggjd6enfk.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('24', '3', 'Jenga Building Tower Game  (Multicolor)', '20', '299', 'https://rukminim1.flixcart.com/image/832/832/jqb8ccw0/block-construction/e/w/s/54-pcs-blocks-4-dices-wooden-tumbling-stacking-jenga-building-original-imaf86xhzb75fwgg.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('25', '3', 'Hot Wheels Rebound Raceway Play Set  (Multicolor)', '20', '2007', 'https://rukminim1.flixcart.com/image/832/832/jhgl5e80/vehicle-pull-along/h/h/f/rebound-raceway-play-set-hot-wheels-original-imaf5hbxjemtxtef.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('26', '3', 'Nightstar Pull Back and Go Metal Car', '20', '745', 'https://rukminim1.flixcart.com/image/832/832/jnw2he80/vehicle-pull-along/v/8/9/pull-back-and-go-metal-car-with-music-and-doors-open-system-min-original-imafag2n7uzauqry.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('27', '3', 'SME EXQUISITE REMOTE CONTROL HELICOPTER HX 713', '20', '899', 'https://rukminim1.flixcart.com/image/832/832/k2gh30w0/remote-control-toy/n/d/b/exquisite-remote-control-helicopter-hx-713-sme-original-imafhss4tcgwpb5k.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('28', '3', 'CEAT Tennis Bat', '20', '290', 'https://rukminim1.flixcart.com/image/832/832/jq5iky80/bat/x/2/x/700-1000-tennis-bat-ball-combo-harrow-na-ceat-original-imaeurksgezbfdvc.jpeg?q=70');
insert into product(product_id, category_id, product_name, quantity, price, image_url) values ('29', '3', 'Raisco One Star Cricket Leather Ball - Size: 3', '20', '199', 'https://rukminim1.flixcart.com/image/832/832/jvjugsw0/ball/n/f/f/153-1-flicks-2-panel-standard-1-flicks-cricket-leather-ball-original-imaf4zhyphzqhpzz.jpeg?q=70');


insert into users(user_id, first_name, last_name, username, email, password) values (random_uuid(), 'John', 'Doe', 'jdoe', 'johndoe@gmail.com', 'jd123!@#');